AWSTemplateFormatVersion: '2010-09-09'
Description: ElasticSearch cluster for NVA.


Resources:
  NVAElasticSearch:
    Type: AWS::Elasticsearch::Domain
    Properties:
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '884807050265'
            Action: 'es:*'
            Resource: 'arn:aws:es::884807050265:domain/*'
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: true
        InstanceCount: 2
        ZoneAwarenessEnabled: true
        InstanceType: t2.medium.elasticsearch
        DedicatedMasterType: t2.medium.elasticsearch
        DedicatedMasterCount: 3
      ElasticsearchVersion: '7.7'
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp2
      CognitoOptions:
        Enabled: false

  ElasticSearchPowerUserRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - es.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonESCognitoAccess

Outputs:
  NVAElasticSearchDomainEndpoint:
    Description: NVA elasticsearch domain endpoint.
    Value: !GetAtt NVAElasticSearch.DomainEndpoint
    Export:
      Name: NVAElasticSearchDomainEndpoint